# Default values for aks-agent-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

aad-pod-identity:
  rbac:
    enabled: false
  installCRDs: true

image:
  name: reidog93/ado-agent
  version: latest

agent:
  replicas: 1

imagePullSecrets:
  name: regsecret

identity:
  name: example-tf-infra-msi
  resource_id: /subscriptions/22222222-2222-2222-2222-222222222222/resourcegroups/example-tf-infra/providers/Microsoft.ManagedIdentity/userAssignedIdentities/example-tf-infra-msi
  client_id: 11111111-1111-1111-1111-111111111111

azdevops:
  # token # AzureDevops Personal access token
  url: https://dev.azure.com/michalchmel
  agent_prefix: aks
  agent_pool: example-agent-pool
  remove_offline: \"true\"

hpa:
  pod_cpu_requests: 100m
  pod_cpu_limits: 300m
  min_pod_count: 2
  max_pod_count: 2
  target_cpu_util_percent: 50

terraform:
  version: 0.13.2
